server:
    port: 2224


eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
#      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/


spring:
    application:
        name: rl-gateway
#    datasource:
#        url: jdbc:mysql://localhost:3306/readlater?serverTimezone=GMT%2B8
#        username: root
#        password: 88888888
#        driver-class-name: com.mysql.cj.jdbc.Driver
#    jpa:
#        show-sql: true
#        hibernate:
#            ddl-auto: update
zuul:
  routes:
    api-a:
      path: /api-a/**
      serciveId: RL-BACKEND

debug: true
